language: php
php:
- '7.3'
- '7.4'

script:
  git grep -l ":git_id:" | xargs sed -e "s/:git_id:/`git describe --abbrev=10 --dirty --always --tags`/"
  git grep -l ":pub_date:" | xargs sed -e "s/:pub_date:/$(date '+%Y-%m-%d %H:%M')/"
  phpunit --bootstrap ./autoload.php --testdox ./test/

env:
  global:
  - secure: llf1htWM28CcfBGFp8zYZi/zsrxZRjTlfch+7nHESaxPQ6z3PFw8YANlwTs71CFVGB5iYBroeviPiCkQqqMOHlZb4aThc+vEqhHuJbFi40G5z2cwcZWuVE+qzLnwGMu7ZJVVxy/67WCIJjW1bcMWkFaIQhWveLz1sRZPixTVMeMSXy/ihrghf7KUFhomZHl+irzkHVNRJZ4UFpiMoauvjDiKNWQMRxZJxWUfkkGKdB68SWBRhmBPAIzA62vg9thVh3+8j5gMJfyijrtThqRA+Yh8NBiUaIZY3ssgvsYKD6Qvi8pPeLwdl7X0DXWPio9Sbux7ioAoFiEp7xrNd8x9ql6s2y0HKGbCMlb332ZflZNnYVDcBkg+yV7BH3aNJrMcbNP57/S+B10Ky9SgM1GzwJs4gy+HfPlugw4KO5PkpuJOAhvBaf5nOkmPHdsxnctmNNwUPe0p4AtI5+agY/KNe7iqlz0kXaL1PyuHQamlI99Qgej0hnF//9RH5gynvC6PaClySJ+1bkLPhx5zXxOfvyLA/FNIR7VMfgsvctVtQP0wOGEH4H1ARAPs+m35sd0aeCpcEEVunw6q3sLESdrk50WO4+dd92oBaJQcIuQm6HBT2DRNWrY1Rn6hJUOLO2mj+16hmzfRGZ/rJNaEWjiTJu1VlH1oM7BqJxj3U2X9wp0=
  - secure: ihH8Ct69uc2y9AZL3NrG4usfv7/8rHFH3dNzOTFhGxdFCdHeaGNZTHJxdxmR1+T3ukzvCkoctnuOqaAh6FKdhEKlxLLcBmcA+SpARAEteKhJJLr21VX8mwKTKtAUA31er+E5NTeeCusoqkUxuWf4OSdRUWF4oTo2yf9HTL0UVqEXh/eLB0kIIO/vy3PrutkYCBHRU3ONgthCHcHNKD1lpayLzcITlXENURJ5YbA+qCYpd2PSJk/bL44vr4bT1hAkhX0IDi039P3PytXTJqS86E3AVxIe7FVVV7ubNrKe0QUjR9DFvLd0aCvV6aZTwLNr35DzOKD8i5PHKL3EyAAl/EOiS5ASQYeWqeDF70Q2Rv77rXjNOV8nC4qAz3Ybny0/P2xxunQ+4ppNBjJ8b+E18GKL4tih8qWkdHVPF9Zsu1WMUf0tkXJMrhTnhIMLmZ1AwUsaSsCoRogINO671GeTda07SOJRB30MY/O5lw/8HISORJTvbHPEK10KHxxpCjOobfBvvpakavvMMquUmTt9jzk6QwqP1kZpLn7wlJYQ7X1Xd/flJPISIXifE89N8xr9or0rXDT66aM3AtsAkjl4tFFs+bKfXNvSbyuwUGY3nW+Lvc7NL6GWygoYDk/4PhJqTRy1XRCpdlRewaW6kDzYU8AHvVFB8R2lGMHjztxkzuo=

after_success:
- curl --ftp-create-dirs -T "{seasonResult,competitionTable,insertComp,resultTables,wineTables}.php"
  -u $FTP_USER:$FTP_PASSW ftp://ftp.lerenius.se/obantour/result/
- curl --ftp-create-dirs -T "src/{Player,Competition}.php" -u $FTP_USER:$FTP_PASSW
  ftp://ftp.lerenius.se/obantour/result/src/
- curl --ftp-create-dirs -T "inc/{NumberOfWines,NumberOfComp,SeasonResult,WinesPerComp,Ranking,Courses}_inc.php"
  -u $FTP_USER:$FTP_PASSW ftp://ftp.lerenius.se/obantour/result/inc/
